[build]
  publish = "."
  command = ""

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=60"

[[headers]]
  for = "/app.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=60"

[[headers]]
  for = "/tile-*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"
